/// Embedded cookbook recipes for the sim-sdk glasses facade.
pub static RECIPES: sim_cookbook::EmbeddedDir = &[
    (
        "book.toml",
        include_bytes!("../../../recipes/glasses/book.toml"),
    ),
    (
        "glasses/chapter.toml",
        include_bytes!("../../../recipes/glasses/chapter.toml"),
    ),
    (
        "glasses/viture-two-rate/README.md",
        include_bytes!("../../../recipes/glasses/viture-two-rate/README.md"),
    ),
    (
        "glasses/viture-two-rate/input.lisp",
        include_bytes!("../../../recipes/glasses/viture-two-rate/input.lisp"),
    ),
    (
        "glasses/viture-two-rate/recipe.toml",
        include_bytes!("../../../recipes/glasses/viture-two-rate/recipe.toml"),
    ),
    (
        "glasses/halo-glance-pager/README.md",
        include_bytes!("../../../recipes/glasses/halo-glance-pager/README.md"),
    ),
    (
        "glasses/halo-glance-pager/input.lisp",
        include_bytes!("../../../recipes/glasses/halo-glance-pager/input.lisp"),
    ),
    (
        "glasses/halo-glance-pager/recipe.toml",
        include_bytes!("../../../recipes/glasses/halo-glance-pager/recipe.toml"),
    ),
    (
        "glasses/voice-site/README.md",
        include_bytes!("../../../recipes/glasses/voice-site/README.md"),
    ),
    (
        "glasses/voice-site/input.lisp",
        include_bytes!("../../../recipes/glasses/voice-site/input.lisp"),
    ),
    (
        "glasses/voice-site/recipe.toml",
        include_bytes!("../../../recipes/glasses/voice-site/recipe.toml"),
    ),
    (
        "glasses/co-use/README.md",
        include_bytes!("../../../recipes/glasses/co-use/README.md"),
    ),
    (
        "glasses/co-use/input.lisp",
        include_bytes!("../../../recipes/glasses/co-use/input.lisp"),
    ),
    (
        "glasses/co-use/recipe.toml",
        include_bytes!("../../../recipes/glasses/co-use/recipe.toml"),
    ),
    (
        "glasses/review-in-space/README.md",
        include_bytes!("../../../recipes/glasses/review-in-space/README.md"),
    ),
    (
        "glasses/review-in-space/input.lisp",
        include_bytes!("../../../recipes/glasses/review-in-space/input.lisp"),
    ),
    (
        "glasses/review-in-space/recipe.toml",
        include_bytes!("../../../recipes/glasses/review-in-space/recipe.toml"),
    ),
];
