/// Embedded cookbook recipes for the sim-sdk reference device.
pub static RECIPES: sim_cookbook::EmbeddedDir = &[
    ("book.toml", include_bytes!("../../../recipes/book.toml")),
    (
        "01-basics/chapter.toml",
        include_bytes!("../../../recipes/01-basics/chapter.toml"),
    ),
    (
        "01-basics/boot-runtime/README.md",
        include_bytes!("../../../recipes/01-basics/boot-runtime/README.md"),
    ),
    (
        "01-basics/boot-runtime/expected.txt",
        include_bytes!("../../../recipes/01-basics/boot-runtime/expected.txt"),
    ),
    (
        "01-basics/boot-runtime/input.lisp",
        include_bytes!("../../../recipes/01-basics/boot-runtime/input.lisp"),
    ),
    (
        "01-basics/boot-runtime/recipe.toml",
        include_bytes!("../../../recipes/01-basics/boot-runtime/recipe.toml"),
    ),
    (
        "device/chapter.toml",
        include_bytes!("../../../recipes/device/chapter.toml"),
    ),
    (
        "device/consent/README.md",
        include_bytes!("../../../recipes/device/consent/README.md"),
    ),
    (
        "device/consent/input.lisp",
        include_bytes!("../../../recipes/device/consent/input.lisp"),
    ),
    (
        "device/consent/recipe.toml",
        include_bytes!("../../../recipes/device/consent/recipe.toml"),
    ),
    (
        "device/route-swap/README.md",
        include_bytes!("../../../recipes/device/route-swap/README.md"),
    ),
    (
        "device/route-swap/input.lisp",
        include_bytes!("../../../recipes/device/route-swap/input.lisp"),
    ),
    (
        "device/route-swap/recipe.toml",
        include_bytes!("../../../recipes/device/route-swap/recipe.toml"),
    ),
    (
        "device/two-rate/README.md",
        include_bytes!("../../../recipes/device/two-rate/README.md"),
    ),
    (
        "device/two-rate/input.lisp",
        include_bytes!("../../../recipes/device/two-rate/input.lisp"),
    ),
    (
        "device/two-rate/recipe.toml",
        include_bytes!("../../../recipes/device/two-rate/recipe.toml"),
    ),
];
