/// Embedded cookbook recipes for the sim-sdk watch facade.
pub static RECIPES: sim_cookbook::EmbeddedDir = &[
    (
        "book.toml",
        include_bytes!("../../../recipes/watch/book.toml"),
    ),
    (
        "watch/chapter.toml",
        include_bytes!("../../../recipes/watch/chapter.toml"),
    ),
    (
        "watch/dual-quorum/README.md",
        include_bytes!("../../../recipes/watch/dual-quorum/README.md"),
    ),
    (
        "watch/dual-quorum/input.lisp",
        include_bytes!("../../../recipes/watch/dual-quorum/input.lisp"),
    ),
    (
        "watch/dual-quorum/recipe.toml",
        include_bytes!("../../../recipes/watch/dual-quorum/recipe.toml"),
    ),
    (
        "watch/glance-pager/README.md",
        include_bytes!("../../../recipes/watch/glance-pager/README.md"),
    ),
    (
        "watch/glance-pager/input.lisp",
        include_bytes!("../../../recipes/watch/glance-pager/input.lisp"),
    ),
    (
        "watch/glance-pager/recipe.toml",
        include_bytes!("../../../recipes/watch/glance-pager/recipe.toml"),
    ),
    (
        "watch/hold-last/README.md",
        include_bytes!("../../../recipes/watch/hold-last/README.md"),
    ),
    (
        "watch/hold-last/input.lisp",
        include_bytes!("../../../recipes/watch/hold-last/input.lisp"),
    ),
    (
        "watch/hold-last/recipe.toml",
        include_bytes!("../../../recipes/watch/hold-last/recipe.toml"),
    ),
    (
        "watch/privacy-reaper/README.md",
        include_bytes!("../../../recipes/watch/privacy-reaper/README.md"),
    ),
    (
        "watch/privacy-reaper/input.lisp",
        include_bytes!("../../../recipes/watch/privacy-reaper/input.lisp"),
    ),
    (
        "watch/privacy-reaper/recipe.toml",
        include_bytes!("../../../recipes/watch/privacy-reaper/recipe.toml"),
    ),
];
