#[cfg(feature = "logic")]
const _: &str = "logic";
#[cfg(feature = "logic-agent")]
const _: &str = "logic-agent";
#[cfg(feature = "logic-numbers")]
const _: &str = "logic-numbers";
#[cfg(feature = "logic-server")]
const _: &str = "logic-server";
#[cfg(any(feature = "logic-wasm", feature = "citizen-strict"))]
const _: &str = "logic-wasm-citizen-strict";
#[cfg(feature = "pitch")]
const _: &str = "pitch";
#[cfg(feature = "pitch-wasm-frame")]
const _: &str = "pitch-wasm-frame";
#[cfg(feature = "midi")]
const _: &str = "midi";
#[rustfmt::skip]
#[cfg(any(feature = "midi-sysex", feature = "midi-wasm-frame", feature = "topology", feature = "topology-agent", feature = "topology-codec", feature = "topology-list", feature = "topology-stream", feature = "topology-table"))]
const _: &str = "midi-topology-feature-sentinels";
#[cfg(feature = "music")]
const _: &str = "music";
#[cfg(feature = "music-analysis")]
const _: &str = "music-analysis";
// The `cookbook` feature needs a cfg sentinel so the contract test can prove the
// feature is visible to conditional compilation.
#[cfg(feature = "cookbook")]
const _: &str = "cookbook";
#[cfg(feature = "device")]
const _: &str = "device";
#[cfg(feature = "watch")]
const _: &str = "watch";
#[cfg(feature = "watch-modeled")]
const _: &str = "watch-modeled";
#[cfg(feature = "watch-hardware")]
const _: &str = "watch-hardware";
#[cfg(feature = "discrete")]
const _: &str = "discrete";
#[cfg(feature = "discrete-algebra")]
const _: &str = "discrete-algebra";
#[cfg(feature = "discrete-graph")]
const _: &str = "discrete-graph";
#[cfg(feature = "discrete-comb")]
const _: &str = "discrete-comb";
#[cfg(feature = "discrete-spectral")]
const _: &str = "discrete-spectral";
#[cfg(feature = "discrete-rank")]
const _: &str = "discrete-rank";
#[cfg(feature = "discrete-music")]
const _: &str = "discrete-music";
#[cfg(feature = "discrete-runtime")]
const _: &str = "discrete-runtime";
#[cfg(feature = "music-lift")]
const _: &str = "music-lift";
#[cfg(feature = "music-notation")]
const _: &str = "music-notation";
#[cfg(feature = "music-stack")]
const _: &str = "music-stack";
#[cfg(feature = "music-stack-wasm-frame")]
const _: &str = "music-stack-wasm-frame";
#[cfg(feature = "music-transform")]
const _: &str = "music-transform";
#[cfg(feature = "music-wasm-frame")]
const _: &str = "music-wasm-frame";
#[cfg(feature = "sound")]
const _: &str = "sound";
#[cfg(feature = "sound-audio-lift")]
const _: &str = "sound-audio-lift";
#[cfg(feature = "sound-bridge")]
const _: &str = "sound-bridge";
#[cfg(feature = "sound-dissonance")]
const _: &str = "sound-dissonance";
#[cfg(feature = "sound-fft")]
const _: &str = "sound-fft";
#[cfg(feature = "sound-gm")]
const _: &str = "sound-gm";
#[cfg(feature = "sound-music")]
const _: &str = "sound-music";
#[cfg(feature = "sound-render")]
const _: &str = "sound-render";
#[cfg(feature = "sound-spectrum")]
const _: &str = "sound-spectrum";
#[cfg(feature = "sound-timbre")]
const _: &str = "sound-timbre";
#[cfg(feature = "sound-tuning")]
const _: &str = "sound-tuning";
#[cfg(feature = "sound-wasm-frame")]
const _: &str = "sound-wasm-frame";
#[cfg(feature = "femm-assembly")]
const _: &str = "femm-assembly";
#[cfg(feature = "femm-codec")]
const _: &str = "femm-codec";
#[cfg(feature = "femm-core")]
const _: &str = "femm-core";
#[cfg(feature = "femm-fixtures")]
const _: &str = "femm-fixtures";
#[cfg(feature = "femm-field")]
const _: &str = "femm-field";
#[cfg(feature = "femm-flow")]
const _: &str = "femm-flow";
#[cfg(feature = "femm-function")]
const _: &str = "femm-function";
#[cfg(feature = "femm-geometry")]
const _: &str = "femm-geometry";
#[cfg(feature = "femm-material")]
const _: &str = "femm-material";
#[cfg(feature = "femm-mesh")]
const _: &str = "femm-mesh";
#[cfg(feature = "femm-ode")]
const _: &str = "femm-ode";
#[cfg(feature = "femm-physics")]
const _: &str = "femm-physics";
#[cfg(feature = "femm-post")]
const _: &str = "femm-post";
#[cfg(feature = "femm-prelude")]
const _: &str = "femm-prelude";
#[cfg(feature = "femm-sensitiv")]
const _: &str = "femm-sensitiv";
#[cfg(feature = "femm-solve")]
const _: &str = "femm-solve";
#[cfg(feature = "femm-space")]
const _: &str = "femm-space";
#[cfg(feature = "femm-tape")]
const _: &str = "femm-tape";
#[cfg(feature = "agent-runner-core")]
const _: &str = "agent-runner-core";
#[cfg(feature = "agent-runner-http")]
const _: &str = "agent-runner-http";
#[cfg(feature = "agent-runner-http-tls")]
const _: &str = "agent-runner-http-tls";
#[cfg(feature = "agent-runner-ollama")]
const _: &str = "agent-runner-ollama";
#[cfg(feature = "agent-runner-process")]
const _: &str = "agent-runner-process";
#[cfg(feature = "genai")]
const _: &str = "genai";
#[cfg(feature = "genai-local")]
const _: &str = "genai-local";
#[cfg(feature = "genai-provider")]
const _: &str = "genai-provider";
#[cfg(feature = "bridge")]
const _: &str = "bridge";
#[cfg(feature = "codec-bridge")]
const _: &str = "codec-bridge";
#[cfg(feature = "codec-chat")]
const _: &str = "codec-chat";
#[cfg(feature = "codec-mcp")]
const _: &str = "codec-mcp";
#[cfg(feature = "scene")]
const _: &str = "scene";
#[cfg(feature = "intent")]
const _: &str = "intent";
#[cfg(feature = "view")]
const _: &str = "view";
#[cfg(feature = "web-layout")]
const _: &str = "web-layout";
#[cfg(feature = "web-bridge")]
const _: &str = "web-bridge";
#[cfg(feature = "web")]
const _: &str = "web";
#[cfg(feature = "web-wasm-frame")]
const _: &str = "web-wasm-frame";
#[cfg(feature = "view-agent")]
const _: &str = "view-agent";
#[cfg(feature = "view-bridge")]
const _: &str = "view-bridge";
#[cfg(feature = "view-doc")]
const _: &str = "view-doc";
#[cfg(feature = "view-math")]
const _: &str = "view-math";
#[cfg(feature = "view-codec")]
const _: &str = "view-codec";
#[cfg(feature = "view-daw")]
const _: &str = "view-daw";
#[cfg(feature = "web-full")]
const _: &str = "web-full";
#[rustfmt::skip]
#[cfg(any(feature = "skill-mcp", feature = "skill-serve", feature = "skill-agent", feature = "skill-openai", feature = "skill-runner", feature = "skill-http", feature = "skill-process", feature = "skill-cache", feature = "skill-cassette", feature = "mcp", feature = "mcp-skill", feature = "mcp-stdio", feature = "mcp-stream", feature = "mcp-http", feature = "mcp-client", feature = "mcp-sampling", feature = "mcp-cassette", feature = "mcp-binary"))]
const _: &str = "mcp-features";
